version: "3.2"
services:
  redis_db:
    image: redis:4.0.8-alpine
    container_name: "redis_db"
    ports:
      - "6379:6379"
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3103:3103"
    depends_on:
      - redis_db
    container_name: "webapp"
